
version: "3.8"    # verzija na docekr koja ja koristam 

services:
  mysql:
    image: mysql:8.0    #ime na servisot
    restart: unless-stopped   # pri pad na azure serverot vedna po podiganje ke se vkluce database
    env_file:       # se dava lokacija od kade da se cita lozinkata
      - ./backend/.env
    environment:    
      MYSQL_DATABASE: ${DB_NAME:-Klinicka_Bolnica_Stip}     #imaeto na bazata, ako ne e postaveno koristeme Klinicka_Bolnica_Stip
    ports:
      - "3306:3306"     # porta na slusanje edna za ured, eden za docker
    volumes:
      - mysql_data:/var/lib/mysql   # povrzuvanje na podatocite od bazata so azure diskovite
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # utf-8 oddeli lekari i makedonski tekst
    healthcheck: # mysqladmin ping
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s    #intervalot za kolku cesto ili na kolku sekundi treba da proveruva dali serverot na the database e zdrav
      timeout: 5s
      retries: 5
  
  backend:    #ime na serverot za api (endpoints)
    build:    # se sostavuva slika
      context: ./backend    # lokacijata deka moze da se pronajde kodot
      dockerfile: Dockerfile    # koja datoteka da ja koriste pri build
    restart: unless-stopped 
    ports:        # backend dostapen na porta 8000
      - "8000:8000"
    env_file:     # vcituvanje na lozinki i klucevi, kaj lakri
      - ./backend/.env
    volumes:      # povrzuvanje na folderot so statickite fajlovi
      - ./backend/static:/app/static


  # Frontend se postavuva na porta 80
  frontend:       # ime na serverot
    image: nginx:alpine   
    restart: unless-stopped
    ports:      # frontend delot e dostapen na porta 80
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro # gi zima html i js fajlovite i gi stava kade sto e nginx servisot
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro    # ja vcituva konfiguracijata, kako se odvivaat baranjata
    depends_on:
      - backend       # pravime komunikacija so docekrot, dokolku backend e pusten, se pusta i frontend. Se ni zavisi od backend (aktiven = aktiven)

volumes:      
  mysql_data:
