
version: "3.8"

services:
  # MySQL – само ако користиш локална база во Docker (раскоментирај depends_on во backend)
  mysql:
    image: mysql:8.0      
    restart: unless-stopped   # pri pad na azure serverot vedna po podiganje ke se vkluce database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpass}  # lozinka, ako nema se zema rootpass
      MYSQL_DATABASE: ${DB_NAME:-Klinicka_Bolnica_Stip}
    ports:
      - "3306:3306"     # porta na slusanje edna za ured, eden za docker
    volumes:
      - mysql_data:/var/lib/mysql   # povrzuvanje na podatocite od bazata so azure diskovite
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci   #utf-8 bidejki oddeli lekari i se drugo vo database mi e na makedonski 
    healthcheck:    # proverka dali bazata raboti na sekoj 5 sekundi 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - with-db

  # Backend (FastAPI) – сервира и API и статички frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:     # kade e smesteno imeto na bazata i lozinkata
      - ./backend/.env
    environment:
      DB_HOST: ${DB_HOST:-mysql}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME:-Klinicka_Bolnica_Stip}
      DB_PORT: ${DB_PORT:-3306}
    volumes:
      - ./backend/static:/app/static
    # depends_on:  # раскоментирај ако користиш mysql сервис
    #   mysql:
    #     condition: service_healthy

  # Frontend se postavuva na porta 80
  frontend:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro   # se dava tocna lokacija do frontend fajlovite 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro    # ja vcituva konfiguracijata, kako se odvivaat baranjata
    depends_on:
      - backend       # frontend ne se aktivira dodeka ne se startuva backend, se ceka start na backend pa potoa na frontend

volumes:
  mysql_data:
