# servero koj gi gleda baranjata i odlucuva dali ke se pratat na backend ili na frontend 
# ako se izbere da se povika html dava frontend, 
# dokolku e potrebna obrabotka na podatoci na primer da se napravi termin se praka na bakcend da go obrabote baranjetow


server {            # glaven blok, kade se smesteni site pravila za stranicata
    listen 80;      # ngnix slusa na porta 80
    server_name _;  # serverot dava odgovor od bilo koja ip adresa ili domen sto pristapuva do nego 
    root /usr/share/nginx/html;     # lokacija vo konte za html, js, css
    index index.html;

    client_max_body_size 50M;       # na adminot mu se dozvoluva prikacuvanje na sliki so max golemina od 50MB, vo delot za novosti

    # FastAPI преку backend: regex location мора да фати /lekari пред „location /“ (иначе се враќа index.html наместо JSON)
    # ako linkot zapocnuva so nekoj od ponudenite svojstva , baranjeto ne go obrabotuva frontend tuku se dava na backend
    location ~ ^/(lekari|pacienti|termini|admin|aparati|specialnosti|uslugi|novosti|kariera|aplikacija|static|docs|openapi\.json|redoc|debug-novosti|debug-kariera|debug-db)(/.*)?$ {
        proxy_pass http://backend:8000;         # baranjeto od klientoto se prepraka na backend sto slusa na porta 8000
        proxy_http_version 1.1;         
        proxy_set_header Host $host;        # pravi prenos na orginaloto ime na domentot
        proxy_set_header X-Real-IP $remote_addr;        # ja dava vistinskata adresa na korisniko, moze da se vide od koj ured ili lokacija na uredot od kade se pristapuva
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;        # lista na site ip adresi niz koj minuva baranjeto. 
        proxy_set_header X-Forwarded-Proto $scheme;         # mu se kazuva na backend delot dali da koriste http ili https
        proxy_read_timeout 120s;        # backend ima vreme od 120s da dade odgovor, ako ne dade se prekinuva vrskata
    }

    location / {        # ova e za linkovite sto ne se obrabotuvat od backend
        try_files $uri $uri/ /index.html;       # se pravi proverka dali postoi takov dajl, ako ne postoi se proveruva dali e folder
                                                # ako ne e nitu edno ja dava index.html
    }
}
