from typing import overload

from mysql.connector.cursor import MySQLCursor, MySQLCursorDict

class MySQLConnection:
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def is_connected(self) -> bool: ...
    @overload
    def cursor(self, *, dictionary: bool = False, **kwargs: object) -> MySQLCursor: ...
    @overload
    def cursor(self, *, dictionary: bool = True, **kwargs: object) -> MySQLCursorDict: ...
