from typing import Any

class MySQLCursor:
    lastrowid: int | None
    rowcount: int
    def execute(self, operation: str, params: tuple[Any, ...] | dict[str, Any] | None = ...) -> None: ...
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    def close(self) -> None: ...

class MySQLCursorDict(MySQLCursor):
    def fetchone(self) -> dict[str, Any] | None: ...
    def fetchall(self) -> list[dict[str, Any]]: ...

RowType = tuple[Any, ...]
